"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const task_controller_1 = require("../controllers/task.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const router = (0, express_1.Router)();
router.get("/", task_controller_1.getAll);
router.get("/:id", task_controller_1.findTaskById);
router.post("/", auth_middleware_1.authMiddleware, task_controller_1.createTask);
router.delete("/:id", auth_middleware_1.authMiddleware, task_controller_1.deleteTaskId);
exports.default = router;
